"""Text normalization and multilingual keyword mapping."""

DISTRICT_MAP = {
    "adilabad": "adilabad",
    "ఆదిలాబాద్": "adilabad",
    "bhadradri kothagudem": "bhadradri-kothagudem",
    "kothagudem": "bhadradri-kothagudem",
    "భద్రాద్రి కొత్తగూడెం": "bhadradri-kothagudem",
    "కొత్తగూడెం": "bhadradri-kothagudem",
    "hanamkonda": "hanamkonda",
    "hanumakonda": "hanamkonda",
    "హనుమకొండ": "hanamkonda",
    "hyderabad": "hyderabad",
    "హైదరాబాద్": "hyderabad",
    "jagtial": "jagtial",
    "జగిత్యాల": "jagtial",
    "jangaon": "jangaon",
    "జనగాం": "jangaon",
    "jayashankar bhupalpally": "jayashankar-bhupalpally",
    "bhupalpally": "jayashankar-bhupalpally",
    "జయశంకర్ భూపాలపల్లి": "jayashankar-bhupalpally",
    "భూపాలపల్లి": "jayashankar-bhupalpally",
    "jogulamba gadwal": "jogulamba-gadwal",
    "gadwal": "jogulamba-gadwal",
    "జోగులాంబ గద్వాల": "jogulamba-gadwal",
    "గద్వాల": "jogulamba-gadwal",
    "kamareddy": "kamareddy",
    "కామారెడ్డి": "kamareddy",
    "karimnagar": "karimnagar",
    "కరీంనగర్": "karimnagar",
    "khammam": "khammam",
    "ఖమ్మం": "khammam",
    "komaram bheem asifabad": "komaram-bheem-asifabad",
    "asifabad": "komaram-bheem-asifabad",
    "కొమరం భీమ్ ఆసిఫాబాద్": "komaram-bheem-asifabad",
    "ఆసిఫాబాద్": "komaram-bheem-asifabad",
    "mahabubabad": "mahabubabad",
    "మహబూబాబాద్": "mahabubabad",
    "mahabubnagar": "mahabubnagar",
    "మహబూబ్ నగర్": "mahabubnagar",
    "మహబూబ్‌నగర్": "mahabubnagar",
    "mancherial": "mancherial",
    "మంచిర్యాల": "mancherial",
    "medak": "medak",
    "మెదక్": "medak",
    "medchal-malkajgiri": "medchal-malkajgiri",
    "medchal": "medchal-malkajgiri",
    "malkajgiri": "medchal-malkajgiri",
    "మేడ్చల్ మల్కాజ్‌గిరి": "medchal-malkajgiri",
    "మేడ్చల్": "medchal-malkajgiri",
    "mulugu": "mulugu",
    "ములుగు": "mulugu",
    "nagarkurnool": "nagarkurnool",
    "నాగర్‌కర్నూల్": "nagarkurnool",
    "nalgonda": "nalgonda",
    "నల్గొండ": "nalgonda",
    "narayanpet": "narayanpet",
    "నారాయణపేట": "narayanpet",
    "nirmal": "nirmal",
    "నిర్మల్": "nirmal",
    "nizamabad": "nizamabad",
    "నిజామాబాద్": "nizamabad",
    "peddapalli": "peddapalli",
    "పెద్దపల్లి": "peddapalli",
    "rajanna sircilla": "rajanna-sircilla",
    "sircilla": "rajanna-sircilla",
    "రాజన్న సిరిసిల్ల": "rajanna-sircilla",
    "సిరిసిల్ల": "rajanna-sircilla",
    "rangareddy": "rangareddy",
    "రంగారెడ్డి": "rangareddy",
    "sangareddy": "sangareddy",
    "సంగారెడ్డి": "sangareddy",
    "siddipet": "siddipet",
    "సిద్దిపేట": "siddipet",
    "suryapet": "suryapet",
    "సూర్యాపేట": "suryapet",
    "vikarabad": "vikarabad",
    "వికారాబాద్": "vikarabad",
    "wanaparthy": "wanaparthy",
    "వనపర్తి": "wanaparthy",
    "warangal": "warangal",
    "వరంగల్": "warangal",
    "yadadri bhuvanagiri": "yadadri-bhuvanagiri",
    "yadadri": "yadadri-bhuvanagiri",
    "bhongir": "yadadri-bhuvanagiri",
    "యాదాద్రి భువనగిరి": "yadadri-bhuvanagiri",
    "యాదాద్రి": "yadadri-bhuvanagiri",
    "భువనగిరి": "yadadri-bhuvanagiri",
}

COMMODITY_MAP = {
    "tomato": "tomato",
    "tomatoes": "tomato",
    "టమాటా": "tomato",
    "టమోటా": "tomato",
    "cotton": "cotton",
    "పత్తి": "cotton",
    "turmeric": "turmeric",
    "పసుపు": "turmeric",
    "paddy": "paddy",
    "rice": "paddy",
    "వరి": "paddy",
    "ధాన్యం": "paddy",
    "maize": "maize",
    "corn": "maize",
    "మొక్కజొన్న": "maize",
    "chilli": "red_chilli",
    "red chilli": "red_chilli",
    "మిరప": "red_chilli",
    "onion": "onion",
    "ఉల్లిపాయ": "onion",
    "groundnut": "groundnut",
    "వేరుశనగ": "groundnut",
}

def extract_district(text: str) -> str | None:
    text_lower = text.lower()
    for key, slug in DISTRICT_MAP.items():
        if key in text_lower:
            return slug
    return None

def extract_commodity(text: str) -> str | None:
    text_lower = text.lower()
    for key, cid in COMMODITY_MAP.items():
        if key in text_lower:
            return cid
    return None
