"""Text normalization and multilingual keyword mapping."""

DISTRICT_MAP = {
    "adilabad": "adilabad",
    "ఆదిలాబాద్": "adilabad",
    "bhadradri kothagudem": "bhadradri-kothagudem",
    "kothagudem": "bhadradri-kothagudem",
    "భద్రాద్రి కొత్తగూడెం": "bhadradri-kothagudem",
    "కొత్తగూడెం": "bhadradri-kothagudem",
    "hanamkonda": "hanamkonda",
    "hanumakonda": "hanamkonda",
    "హనుమకొండ": "hanamkonda",
    "hyderabad": "hyderabad",
    "హైదరాబాద్": "hyderabad",
    "jagtial": "jagtial",
    "జగిత్యాల": "jagtial",
    "jangaon": "jangaon",
    "జనగాం": "jangaon",
    "jayashankar bhupalpally": "jayashankar-bhupalpally",
    "bhupalpally": "jayashankar-bhupalpally",
    "జయశంకర్ భూపాలపల్లి": "jayashankar-bhupalpally",
    "భూపాలపల్లి": "jayashankar-bhupalpally",
    "jogulamba gadwal": "jogulamba-gadwal",
    "gadwal": "jogulamba-gadwal",
    "జోగులాంబ గద్వాల": "jogulamba-gadwal",
    "గద్వాల": "jogulamba-gadwal",
    "kamareddy": "kamareddy",
    "కామారెడ్డి": "kamareddy",
    "karimnagar": "karimnagar",
    "కరీంనగర్": "karimnagar",
    "khammam": "khammam",
    "ఖమ్మం": "khammam",
    "komaram bheem asifabad": "komaram-bheem-asifabad",
    "asifabad": "komaram-bheem-asifabad",
    "కొమరం భీమ్ ఆసిఫాబాద్": "komaram-bheem-asifabad",
    "ఆసిఫాబాద్": "komaram-bheem-asifabad",
    "mahabubabad": "mahabubabad",
    "మహబూబాబాద్": "mahabubabad",
    "mahabubnagar": "mahabubnagar",
    "మహబూబ్ నగర్": "mahabubnagar",
    "మహబూబ్‌నగర్": "mahabubnagar",
    "mancherial": "mancherial",
    "మంచిర్యాల": "mancherial",
    "medak": "medak",
    "మెదక్": "medak",
    "medchal-malkajgiri": "medchal-malkajgiri",
    "medchal": "medchal-malkajgiri",
    "malkajgiri": "medchal-malkajgiri",
    "మేడ్చల్ మల్కాజ్‌గిరి": "medchal-malkajgiri",
    "మేడ్చల్": "medchal-malkajgiri",
    "mulugu": "mulugu",
    "ములుగు": "mulugu",
    "nagarkurnool": "nagarkurnool",
    "నాగర్‌కర్నూల్": "nagarkurnool",
    "nalgonda": "nalgonda",
    "నల్గొండ": "nalgonda",
    "narayanpet": "narayanpet",
    "నారాయణపేట": "narayanpet",
    "nirmal": "nirmal",
    "నిర్మల్": "nirmal",
    "nizamabad": "nizamabad",
    "నిజామాబాద్": "nizamabad",
    "peddapalli": "peddapalli",
    "పెద్దపల్లి": "peddapalli",
    "rajanna sircilla": "rajanna-sircilla",
    "sircilla": "rajanna-sircilla",
    "రాజన్న సిరిసిల్ల": "rajanna-sircilla",
    "సిరిసిల్ల": "rajanna-sircilla",
    "rangareddy": "rangareddy",
    "రంగారెడ్డి": "rangareddy",
    "sangareddy": "sangareddy",
    "సంగారెడ్డి": "sangareddy",
    "siddipet": "siddipet",
    "సిద్దిపేట": "siddipet",
    "suryapet": "suryapet",
    "సూర్యాపేట": "suryapet",
    "vikarabad": "vikarabad",
    "వికారాబాద్": "vikarabad",
    "wanaparthy": "wanaparthy",
    "వనపర్తి": "wanaparthy",
    "warangal": "warangal",
    "వరంగల్": "warangal",
    "yadadri bhuvanagiri": "yadadri-bhuvanagiri",
    "yadadri": "yadadri-bhuvanagiri",
    "bhongir": "yadadri-bhuvanagiri",
    "యాదాద్రి భువనగిరి": "yadadri-bhuvanagiri",
    "యాదాద్రి": "yadadri-bhuvanagiri",
    "భువనగిరి": "yadadri-bhuvanagiri",
}

COMMODITY_MAP = {
    # Vegetables
    "tomato": "Tomato",
    "tomatoes": "Tomato",
    "tamatar": "Tomato",
    "టమాటా": "Tomato",
    "టమోటా": "Tomato",
    "onion": "Onion",
    "onions": "Onion",
    "pyaz": "Onion",
    "ఉల్లిపాయ": "Onion",
    "ఉల్లి": "Onion",
    "potato": "Potato",
    "potatoes": "Potato",
    "aloo": "Potato",
    "alu": "Potato",
    "బంగాళాదుంప": "Potato",
    "ఆలు": "Potato",
    "green chilli": "Green Chilli",
    "green chili": "Green Chilli",
    "hari mirch": "Green Chilli",
    "పచ్చి మిరప": "Green Chilli",
    "పచ్చిమిర్చి": "Green Chilli",
    "brinjal": "Brinjal",
    "eggplant": "Brinjal",
    "baingan": "Brinjal",
    "వంకాయ": "Brinjal",
    "bhendi": "Bhendi",
    "ladies finger": "Bhendi",
    "lady finger": "Bhendi",
    "okra": "Bhendi",
    "bhindi": "Bhendi",
    "బెండకాయ": "Bhendi",
    "cabbage": "Cabbage",
    "patta gobhi": "Cabbage",
    "క్యాబేజీ": "Cabbage",
    "క్యాబేజి": "Cabbage",
    "cauliflower": "Cauliflower",
    "phool gobhi": "Cauliflower",
    "కాలీఫ్లవర్": "Cauliflower",
    "carrot": "Carrot",
    "gajar": "Carrot",
    "క్యారెట్": "Carrot",
    "ginger": "Ginger",
    "adrak": "Ginger",
    "అల్లం": "Ginger",
    "garlic": "Garlic",
    "lahsun": "Garlic",
    "వెల్లుల్లి": "Garlic",
    "bitter gourd": "Bitter Gourd",
    "karela": "Bitter Gourd",
    "కాకరకాయ": "Bitter Gourd",
    "bottle gourd": "Bottle Gourd",
    "lauki": "Bottle Gourd",
    "సొరకాయ": "Bottle Gourd",
    "ఆనపకాయ": "Bottle Gourd",
    "ridge gourd": "Ridge Gourd",
    "turai": "Ridge Gourd",
    "బీరకాయ": "Ridge Gourd",
    "drumstick": "Drumstick",
    "sahjan": "Drumstick",
    "మునగకాయ": "Drumstick",
    "ములక్కాడ": "Drumstick",
    "capsicum": "Capsicum",
    "bell pepper": "Capsicum",
    "shimla mirch": "Capsicum",
    "క్యాప్సికం": "Capsicum",

    # Commercial & Cash Crops
    "cotton": "Cotton",
    "kapas": "Cotton",
    "పత్తి": "Cotton",
    "sugarcane": "Sugarcane",
    "ganna": "Sugarcane",
    "చెరకు": "Sugarcane",
    "soybean": "Soybean",
    "soya": "Soybean",
    "సోయాబీన్": "Soybean",
    "సోయా": "Soybean",
    "castor seed": "Castor Seed",
    "castor": "Castor Seed",
    "arandi": "Castor Seed",
    "ఆముదాలు": "Castor Seed",
    "tobacco": "Tobacco",
    "tambaku": "Tobacco",
    "పొగాకు": "Tobacco",

    # Spices
    "turmeric": "Turmeric",
    "haldi": "Turmeric",
    "పసుపు": "Turmeric",
    "red chilli": "Red Chilli",
    "red chili": "Red Chilli",
    "chilli": "Red Chilli",
    "chili": "Red Chilli",
    "mirchi": "Red Chilli",
    "lal mirch": "Red Chilli",
    "మిరప": "Red Chilli",
    "ఎర్ర మిరప": "Red Chilli",
    "ఎండు మిరప": "Red Chilli",
    "coriander": "Coriander",
    "dhania": "Coriander",
    "ధనియాలు": "Coriander",
    "కొత్తిమీర": "Coriander",
    "cumin": "Cumin",
    "jeera": "Cumin",
    "జీలకర్ర": "Cumin",
    "జీరా": "Cumin",
    "black pepper": "Black Pepper",
    "kali mirch": "Black Pepper",
    "మిరియాలు": "Black Pepper",

    # Cereals & Millets
    "paddy": "Paddy / Rice",
    "rice": "Paddy / Rice",
    "dhaan": "Paddy / Rice",
    "chawal": "Paddy / Rice",
    "వరి": "Paddy / Rice",
    "ధాన్యం": "Paddy / Rice",
    "బియ్యం": "Paddy / Rice",
    "maize": "Maize",
    "corn": "Maize",
    "makka": "Maize",
    "మొక్కజొన్న": "Maize",
    "jowar": "Jowar",
    "sorghum": "Jowar",
    "జొన్నలు": "Jowar",
    "జొన్న": "Jowar",
    "bajra": "Bajra",
    "pearl millet": "Bajra",
    "సజ్జలు": "Bajra",
    "ragi": "Ragi",
    "finger millet": "Ragi",
    "రాగులు": "Ragi",
    "తైదలు": "Ragi",
    "wheat": "Wheat",
    "gehu": "Wheat",
    "గోధుమలు": "Wheat",
    "గోధుమ": "Wheat",

    # Pulses
    "bengal gram": "Bengal Gram",
    "chickpea": "Bengal Gram",
    "chana": "Bengal Gram",
    "శనగలు": "Bengal Gram",
    "red gram": "Red Gram / Tur",
    "tur": "Red Gram / Tur",
    "arhar": "Red Gram / Tur",
    "toor": "Red Gram / Tur",
    "కందులు": "Red Gram / Tur",
    "green gram": "Green Gram",
    "moong": "Green Gram",
    "mung": "Green Gram",
    "పెసలు": "Green Gram",
    "black gram": "Black Gram",
    "urad": "Black Gram",
    "మినుములు": "Black Gram",

    # Oilseeds
    "groundnut": "Groundnut",
    "peanut": "Groundnut",
    "moongfali": "Groundnut",
    "వేరుశనగ": "Groundnut",
    "పల్లీలు": "Groundnut",
    "sunflower": "Sunflower",
    "surajmukhi": "Sunflower",
    "పొద్దుతిరుగుడు": "Sunflower",
    "sesame": "Sesame",
    "til": "Sesame",
    "నువ్వులు": "Sesame",
    "mustard": "Mustard",
    "sarson": "Mustard",
    "rai": "Mustard",
    "ఆవాలు": "Mustard",
    "safflower": "Safflower",
    "kardi": "Safflower",
    "కుసుమలు": "Safflower",

    # Fruits
    "mango": "Mango",
    "aam": "Mango",
    "మామిడి": "Mango",
    "sweet orange": "Sweet Orange",
    "mosambi": "Sweet Orange",
    "బత్తాయి": "Sweet Orange",
    "banana": "Banana",
    "kela": "Banana",
    "అరటి": "Banana",
    "papaya": "Papaya",
    "papita": "Papaya",
    "బొప్పాయి": "Papaya",
    "guava": "Guava",
    "amrood": "Guava",
    "జామకాయ": "Guava",
    "జామ": "Guava",
    "watermelon": "Watermelon",
    "tarbooj": "Watermelon",
    "పుచ్చకాయ": "Watermelon",
    "pomegranate": "Pomegranate",
    "anaar": "Pomegranate",
    "anar": "Pomegranate",
    "దానిమ్మ": "Pomegranate",
    "lemon": "Lemon",
    "lime": "Lemon",
    "nimbu": "Lemon",
    "నిమ్మకాయ": "Lemon",
    "నిమ్మ": "Lemon",
}

def extract_district(text: str) -> str | None:
    text_lower = text.lower()
    for key, slug in DISTRICT_MAP.items():
        if key in text_lower:
            return slug
    return None

def extract_commodity(text: str) -> str | None:
    text_lower = text.lower()
    # Sort keys by length descending so multi-word matches take precedence
    for key in sorted(COMMODITY_MAP.keys(), key=len, reverse=True):
        if key in text_lower:
            return COMMODITY_MAP[key]
    return None
